# Generated by Django 6.0.2 on 2026-03-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('reference', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('MESSAGE', 'message'), ('EMAIL', 'email')], default='EMAIL', max_length=120)),
                ('event_type', models.CharField(default='EMAIL', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
