# Generated by Django 6.0.2 on 2026-03-06 09:22

import django.db.models.deletion
import uuid
import wallet.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('account_number', models.CharField(default=wallet.utils.generate_account_number, max_length=10, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('NGN', 'NAIRA'), ('USD', 'DOLLAR'), ('EUR', 'EURO')], default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('FROZEN', 'Frozen'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('ACTIVE', 'Active'), ('CLOSED', 'closed')], default='ACTIVE', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=wallet.utils.generate_reference_id, max_length=20)),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_status', models.CharField(choices=[('PENDING', 'pending'), ('SUCCESSFUL', 'successful'), ('FAILED', 'failed')], max_length=100)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='wallet.wallet')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='wallet.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='wallet.wallet')),
            ],
        ),
    ]
